swagger: "2.0"
info:
  description: This is an Api server for MIRIM IT SHOW entry 'Scanus'.  You can find out more about     Scanus at [https://github.com/mirimitshow](https://github.com/mirimitshow).
  version: 1.0.0
  title: Scanus
  contact:
    email: wisemuji@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /wisemuji/Scanus/1.0.0
schemes:
- https
- http
paths:
  /signup:
    post:
      tags:
      - Auth
      summary: Signing up user
      description: ""
      operationId: signup
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: Users object
        description: Put new Users object
        required: false
        schema:
          $ref: '#/definitions/Users'
      responses:
        200:
          description: user signed up
        400:
          description: invalid input, object invalid
        409:
          description: user already exists
  /signin:
    post:
      tags:
      - Auth
      summary: Signing in user
      description: ""
      operationId: signin
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: email
        in: query
        description: The user email for login
        required: true
        type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        type: string
      responses:
        200:
          description: user logined
        400:
          description: invalid input, object invalid
  /setGroup:
    post:
      tags:
      - Group
      summary: Add new Group
      description: ""
      operationId: setGroup
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: Groups object
        description: Put new Group object(key "token" is autogenerated)
        required: false
        schema:
          $ref: '#/definitions/Groups'
      responses:
        200:
          description: new group added
        400:
          description: invalid input, object invalid
        409:
          description: group already exists
  /getGroup/<token>:
    get:
      tags:
      - Group
      summary: Find existing Group
      description: ""
      operationId: getGroup
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: The token of group to be found
        required: true
        type: string
      responses:
        200:
          description: returns existing Group
          schema:
            $ref: '#/definitions/Groups'
        400:
          description: invalid input, object invalid
  /getUser/<email>:
    get:
      tags:
      - User
      summary: Get user info
      description: ""
      operationId: getUser
      produces:
      - application/json
      parameters:
      - name: email
        in: query
        description: The email of user
        required: true
        type: string
      responses:
        200:
          description: returns user
          schema:
            $ref: '#/definitions/Users'
        400:
          description: invalid input, object invalid
  /getUserGroups/<email>:
    get:
      tags:
      - User
      summary: Find User's Groups
      description: ""
      operationId: getUserGroups
      produces:
      - application/json
      parameters:
      - name: email
        in: query
        description: The email of user
        required: true
        type: string
      responses:
        200:
          description: returns user's Groups
          schema:
            $ref: '#/definitions/GroupsArray'
        400:
          description: invalid input, object invalid
  /joinGroup:
    post:
      tags:
      - Group
      summary: Members can join Group
      description: ""
      operationId: joinGroup
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: The token of group
        required: true
        type: string
      - name: email
        in: query
        description: The email of user
        required: true
        type: string
      responses:
        200:
          description: success joined group
        400:
          description: invalid input, object invalid
  /setTimetable:
    post:
      tags:
      - Group
      summary: Set Group's timetable
      description: ""
      operationId: setTimetable
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: The token of group to be set
        required: true
        type: string
      - name: img
        in: query
        description: The token of group to be set
        required: true
        type: string
      responses:
        200:
          description: returns existing Group
          schema:
            $ref: '#/definitions/Groups'
        400:
          description: invalid input, object invalid
  /setBoard:
    post:
      tags:
      - Board
      summary: Add new board in group
      description: ""
      operationId: setBoard
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: Boards object
        description: Put new Boards object. (Date is not nessessary)
        required: false
        schema:
          $ref: '#/definitions/Boards'
      responses:
        200:
          description: new board Ssuccessfully added
        400:
          description: invalid input, object invalid
        409:
          description: duplicated board
  /getBoard/<token>:
    get:
      tags:
      - Board
      summary: Get one board by token
      description: ""
      operationId: getBoard
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: The token of board
        required: true
        type: string
      responses:
        200:
          description: new board Ssuccessfully added
          schema:
            $ref: '#/definitions/Boards'
        400:
          description: invalid input, object invalid
        409:
          description: duplicated board
  /getGroupBoards/<token>:
    get:
      tags:
      - Board
      summary: Find Group's Boards
      description: ""
      operationId: getUserBoards
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: The token of group
        required: true
        type: string
      responses:
        200:
          description: returns user's Groups
          schema:
            $ref: '#/definitions/BoardsArray'
        209:
          description: No board found
        400:
          description: invalid input, object invalid
  /setScan:
    post:
      tags:
      - Scan
      summary: Add new Scanned image in group
      description: ""
      operationId: setScan
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: Scans object
        description: Put new Scans object.
        required: false
        schema:
          $ref: '#/definitions/Scans'
      responses:
        200:
          description: new scan Ssuccessfully added
        400:
          description: invalid input, object invalid
        409:
          description: duplicated scan
  /getScans/<email>/<cartegory>:
    get:
      tags:
      - Scan
      summary: Get User's Scanned images by cartegory
      description: ""
      operationId: getScans
      produces:
      - application/json
      parameters:
      - name: email
        in: query
        description: The email of user
        required: true
        type: string
      - name: cartegory
        in: query
        description: The cartegory of image
        required: true
        type: string
      responses:
        200:
          description: returns user's Scanned images
          schema:
            $ref: '#/definitions/ScansArray'
        209:
          description: No Scanned images found
        400:
          description: invalid input, object invalid
definitions:
  Users:
    type: object
    required:
    - email
    - name
    - password
    - phone
    properties:
      name:
        type: string
        example: Suhyeon Kim
      email:
        type: string
        format: email
        example: te@st.com
      phone:
        type: string
        example: 010-0000-0000
      password:
        type: string
        example: "0000"
      group:
        type: array
        description: token of user's groups
        items:
          $ref: '#/definitions/Users_group'
      cartegory:
        type: array
        description: cartegory of user's scanned images
        items:
          $ref: '#/definitions/Users_cartegory'
  Groups:
    required:
    - name
    - token
    properties:
      token:
        type: string
        example: rsdcx98wefsdcxz
      name:
        type: string
        example: Happy Group
      members:
        type: array
        description: token of group's members
        items:
          $ref: '#/definitions/Groups_members'
      boards:
        type: array
        description: token of group's boards
        items:
          $ref: '#/definitions/Users_group'
      timetable:
        $ref: '#/definitions/Groups_timetable'
      image:
        $ref: '#/definitions/Groups_image'
  GroupsArray:
    properties:
      groups:
        type: array
        description: array of groups
        items:
          $ref: '#/definitions/Groups'
  Boards:
    required:
    - author
    - content
    - group_token
    - isNotice
    - title
    - token
    properties:
      token:
        type: string
        example: fink32jbkj2kjde
        description: board's token
      group_token:
        type: string
        example: rsdcx98wefsdcxz
        description: group's token
      isNotice:
        type: string
        example: "true"
        description: check the board if it's notice
      author:
        type: string
        example: 김수현
      title:
        type: string
        example: Nice Board
      content:
        type: string
        example: Haha
      date:
        type: string
        example: 2018-11-28T09:08:28.758Z
        description: board's token
      image:
        $ref: '#/definitions/Boards_image'
  BoardsArray:
    properties:
      boards:
        type: array
        description: array of boards
        items:
          $ref: '#/definitions/Boards'
  Scans:
    required:
    - cartegory
    - email
    - id
    - name
    - url
    properties:
      email:
        type: string
        example: test@test.com
        description: email of current user
      cartegory:
        type: string
        example: 영어
        description: cartegory of scanned image
      name:
        type: string
        example: 영어 이미지
        description: name of scanned image
      id:
        type: string
        example: 1558005653449.png
      url:
        type: string
        example: images/scan/1558005653449.png
  ScansArray:
    properties:
      scans:
        type: array
        description: array of scans
        items:
          $ref: '#/definitions/Scans'
  Users_group:
    properties:
      token:
        type: string
        example: iu2k343kj223lk
  Users_cartegory:
    properties:
      name:
        type: string
        example: 영어
  Groups_members:
    properties:
      email:
        type: string
        example: iu2k343kj223lk
  Groups_timetable:
    properties:
      id:
        type: string
      url:
        type: string
    description: id and url of group's timetable image
  Groups_image:
    properties:
      id:
        type: string
      url:
        type: string
    description: id and url of group's image
  Boards_image:
    properties:
      id:
        type: string
      url:
        type: string
    description: image id and url of board's image
